In [151]:
# importing libraries
import numpy as np
import pandas as pd

In [152]:
#Importing the datasets
college_df = pd.read_csv('college_df_final_scores.csv')
college_df_id = college_df
college_df_id.head()

,Unnamed: 0,pos,year,player_name,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,...,ast/tov,rimmade/(rimmade+rimmiss),midmade/(midmade+midmiss),drtg,dporpag,stops,bpm,obpm,dbpm,gbpm
0,0,Pure PG,2016,aakim saintil,99.7,25.1,42.4,51.19,1.4,6.9,...,1.622245,0.4955,0.3651,105.915,1.56664,159.624,-3.26644,0.030543,-3.296980,-2.77093
1,1,Scoring PG,2014,aakim saintil,90.7,18.8,38.8,45.78,2.4,7.2,...,1.186039,0.4000,0.2941,107.276,1.69099,104.720,-2.51437,-1.580690,-0.933676,-3.76000
2,3,Scoring PG,2020,aamahne santos,91.3,16.9,43.4,45.46,1.0,7.5,...,1.500029,0.3333,0.4286,102.478,2.24427,127.305,-2.76325,-1.505430,-1.257820,-3.09113
3,4,Combo G,2019,aamahne santos,94.8,13.6,44.5,48.35,1.3,5.7,...,1.591889,0.4400,0.3404,110.180,1.70602,124.297,-4.17925,-1.570270,-2.608980,-4.17229
4,5,Pure PG,2010,aamir mccleary,83.4,27.1,39.2,43.97,1.9,12.7,...,1.355276,0.4524,0.3162,109.014,1.84381,123.324,-3.70329,-1.809020,-1.894260,-4.48713

In [153]:
college_df_id.drop('pfr',axis=1, inplace=True)
college_df_id.drop('FT_per',axis=1, inplace=True)
college_df_id.drop('Unnamed: 0',axis=1, inplace=True)
college_df_id = college_df_id.drop('TS_per',axis=1)
college_df_id = college_df_id.drop('ORB_per',axis=1)
college_df_id = college_df_id.drop('DRB_per',axis=1)
college_df_id = college_df_id.drop('AST_per',axis=1)
college_df_id = college_df_id.drop('twoPM',axis=1)
college_df_id = college_df_id.drop('twoPA',axis=1)
college_df_id = college_df_id.drop('twoP_per',axis=1)
college_df_id = college_df_id.drop('TPM',axis=1)
college_df_id = college_df_id.drop('TPA',axis=1)
college_df_id = college_df_id.drop('blk_per',axis=1)
college_df_id = college_df_id.drop('TP_per',axis=1)
college_df_id = college_df_id.drop('stl_per',axis=1)
college_df_id = college_df_id.drop('ftr',axis=1)
#college_df_id = college_df_id.drop('pfr',axis=1)
college_df_id = college_df_id.drop('TO_per',axis=1)
college_df_id = college_df_id.drop('ogbpm',axis=1)
college_df_id = college_df_id.drop('dgbpm',axis=1)
college_df_id = college_df_id.drop('oreb',axis=1)
college_df_id = college_df_id.drop('dreb',axis=1)
college_df_id = college_df_id.drop('treb',axis=1)
college_df_id = college_df_id.drop('ast',axis=1)
college_df_id = college_df_id.drop('stl',axis=1)
college_df_id = college_df_id.drop('porpag',axis=1)
college_df_id = college_df_id.drop('blk',axis=1)
college_df_id = college_df_id.drop('unk',axis=1)
college_df_id = college_df_id.drop('stops',axis=1)
college_df_id = college_df_id.drop('rimmade/(rimmade+rimmiss)',axis=1)
college_df_id = college_df_id.drop('midmade/(midmade+midmiss)',axis=1)
college_df_id = college_df_id.drop('bpm',axis=1)
college_df_id = college_df_id.drop('obpm',axis=1)
college_df_id = college_df_id.drop('dbpm',axis=1)
college_df_id = college_df_id.drop('gbpm',axis=1)
college_df_id = college_df_id.drop('usg',axis=1)
college_df_id = college_df_id.drop('adjoe',axis=1)
college_df_id = college_df_id.drop('mp',axis=1)
college_df_id = college_df_id.drop('pts',axis=1)
college_df_id = college_df_id.drop('ast/tov',axis=1)
college_df_id = college_df_id.drop('adrtg',axis=1)
college_df_id = college_df_id.drop('drtg',axis=1)
college_df_id = college_df_id.drop('Ortg',axis=1)

college_df_id = college_df_id.drop('pos',axis=1)
college_df_id = college_df_id.drop('year',axis=1)
college_df_id = college_df_id.drop('eFG',axis=1)
college_df_id = college_df_id.drop('season',axis=1)
college_df_id = college_df_id.drop('dporpag',axis=1)

college_df_id.head()

      player_name
0   aakim saintil
1   aakim saintil
2  aamahne santos
3  aamahne santos
4  aamir mccleary

In [154]:
college_df_id = college_df_id.drop_duplicates()

In [155]:
college_df_id.head(10)

       player_name
0    aakim saintil
2   aamahne santos
4   aamir mccleary
5      aamir simms
8      aanen moody
9     aaren edmead
10  aaric armstead
14    aaric murray
17    aaron adeoye
18  aaron anderson

In [156]:
#college_df_id.to_csv('id_df.csv')
college_df_id = pd.read_csv('id_df.csv', index_col=0)
college_df_id

                   id
player_name
aakim saintil       0
aamahne santos      2
aamir mccleary      4
aamir simms         5
aanen moody         8
...               ...
zoran talley    22429
zuri james      22430
zvonko buljan   22431
zylan cheatham  22432
zyon pullin     22435

[11214 rows x 1 columns]

In [157]:
names = college_df['player_name'].values
names

array(['aakim saintil', 'aakim saintil', 'aamahne santos', ...,
       'zylan cheatham', 'zyon pullin', 'zyon pullin'], dtype=object)

In [158]:
names_id = college_df_id.to_dict()['id']
names_id

{'aakim saintil': 0,
 'aamahne santos': 2,
 'aamir mccleary': 4,
 'aamir simms': 5,
 'aanen moody': 8,
 'aaren edmead': 9,
 'aaric armstead': 10,
 'aaric murray': 14,
 'aaron adeoye': 17,
 'aaron anderson': 18,
 'aaron augustin': 27,
 'aaron bacote': 28,
 'aaron bodager': 32,
 'aaron bowen': 34,
 'aaron brackett': 35,
 'aaron brennan': 36,
 'aaron bright': 37,
 'aaron broussard': 40,
 'aaron brown': 43,
 'aaron calixte': 47,
 'aaron carter': 51,
 'aaron carver': 52,
 'aaron clarke': 54,
 'aaron clayborn': 58,
 'aaron cook': 59,
 'aaron cosby': 62,
 'aaron craft': 65,
 'aaron dotson': 69,
 'aaron duhart': 70,
 'aaron epps': 71,
 'aaron estrada': 72,
 'aaron falzon': 73,
 'aaron fuller': 75,
 'aaron gordon': 76,
 'aaron graham': 77,
 'aaron harrison': 80,
 'aaron hawley': 82,
 'aaron henry': 84,
 'aaron hines': 87,
 'aaron holiday': 89,
 'aaron johnson': 92,
 'aaron jones': 94,
 'aaron jordan': 95,
 'aaron menzies': 96,
 'aaron mitchell': 97,
 'aaron moore': 99,
 'aaron morgan': 100,
 'aaron nesmith': 101,
 'aaron nettles': 102,
 'aaron parks': 103,
 'aaron pogue': 105,
 'aaron ray': 108,
 'aaron ross': 109,
 'aaron rountree': 110,
 'aaron scales': 111,
 'aaron simpson': 112,
 'aaron tate': 113,
 'aaron thomas': 115,
 'aaron thompson': 116,
 'aaron urbanus': 121,
 'aaron valdes': 125,
 'aaron wheeler': 127,
 'aaron white': 130,
 'aaron wiggins': 134,
 'aaron young': 137,
 'aaryn rai': 139,
 'aaseem dixon': 141,
 'abayomi iyiola': 143,
 'abdel nader': 144,
 'abdoul karim coulibaly': 146,
 'abdoulaye gueye': 147,
 'abdoulaye harouna': 148,
 'abdul ado': 149,
 'abdul alatishe': 153,
 'abdul gaddy': 154,
 'abdul lewis': 156,
 'abdul malik abu': 160,
 'abdul mohamed': 162,
 'abdulai bundu': 164,
 'abe lodwick': 166,
 'abel porter': 167,
 'abner moreira': 169,
 'abou ousmane': 171,
 'aboubacar traore': 172,
 'abu kigab': 173,
 'ac reid': 175,
 'adam brown': 177,
 'adam constantine': 178,
 'adam flagler': 179,
 'adam fletcher': 182,
 'adam folker': 183,
 'adam grant': 185,
 'adam kemp': 189,
 'adam koch': 192,
 'adam kunkel': 193,
 'adam leonard': 195,
 'adam link': 197,
 'adam lonon': 199,
 'adam lulka': 200,
 'adam mcdermott': 201,
 'adam miller': 202,
 'adam nigon': 203,
 'adam parzych': 205,
 'adam pegg': 206,
 'adam pickett': 208,
 'adam seiko': 210,
 'adam smith': 211,
 'adam sollazzo': 214,
 'adam templeton': 216,
 'adam thistlewood': 217,
 'adam waddell': 220,
 'adam weary': 222,
 'adam wing': 226,
 'adam woodbury': 229,
 'adam young': 231,
 'adama adams': 232,
 'adama sanogo': 234,
 'addison spruill': 235,
 'ade murkey': 237,
 'adham eleeda': 240,
 'adhar mayen': 241,
 'adjehi baru': 242,
 'admassu williams': 246,
 'admiral schofield': 247,
 'admon gilder': 249,
 'adnan hodzic': 253,
 'adom jacko': 255,
 'adonis arms': 256,
 'adonis burbage': 257,
 'adonis de la rosa': 260,
 'adonis filer': 261,
 'adonis thomas': 263,
 'adonys henriquez': 264,
 'adreian payne': 266,
 'adrian baldwin jr': 268,
 'adrian bowie': 270,
 'adrian delph': 271,
 'adrian diaz': 274,
 'adrian hicks': 276,
 'adrian nelson': 277,
 'adrian oliver': 278,
 'adrian powell': 280,
 'adrian rich': 283,
 'adrian rodgers': 284,
 'adrian satchell': 287,
 'adrian thomas': 289,
 'adrian williams': 291,
 'adrick mckinney': 293,
 'adrien coleman': 294,
 'adrio bailey': 296,
 'aerris smith': 297,
 'agunwa okolie': 298,
 'ahamadou fofana': 300,
 'aher uguak': 302,
 'ahmaad rorie': 306,
 'ahmad abdullah': 309,
 'ahmad caver': 311,
 'ahmad clark': 314,
 'ahmad frost': 316,
 'ahmad grant': 319,
 'ahmad starks': 321,
 'ahmad thomas': 325,
 'ahmad walker': 328,
 'ahman fells': 330,
 'ahmed ali': 331,
 'ahmed hill': 333,
 'ahmil flowers': 337,
 'ahsan asadullah': 338,
 'ahsante shivers': 341,
 'aidas kavaliauskas': 342,
 'aj banks': 343,
 'aj bramah': 345,
 'aj brodeur': 347,
 'aj caldwell': 351,
 'aj davis': 354,
 'aj english': 359,
 'aj green': 362,
 'aj griffin': 365,
 'aj hammons': 366,
 'aj hardeman': 370,
 'aj harris': 373,
 'aj hess': 375,
 'aj hicks': 379,
 'aj hoggard': 380,
 'aj jacobson': 381,
 'aj john': 385,
 'aj lawson': 386,
 'aj merriweather': 393,
 'aj mosby': 396,
 'aj ogilvy': 398,
 'aj oliver ii': 399,
 'aj pacher': 401,
 'aj plitzuweit': 402,
 'aj reeves': 403,
 'aj riley': 405,
 'aj rompza': 406,
 'aj slaughter': 409,
 'aj smith': 410,
 'aj spencer': 411,
 'aj staton mccray': 413,
 'aj sumbry': 414,
 'aj turner': 415,
 'aj tyler': 419,
 'aj walker': 420,
 'aj walton': 424,
 'aj west': 427,
 'aj wilson': 428,
 'ajani kennedy': 430,
 'ajare sanni': 431,
 'ajay mitchell': 433,
 'ajay sanders': 434,
 'ajdin penava': 436,
 'ajiri ogemuno johnson': 437,
 'akeem bennett': 438,
 'akeem ellis': 440,
 'akeem johnson': 442,
 'akeem richmond': 445,
 'akeem springs': 448,
 'akeem williams': 451,
 'akil mitchell': 452,
 'akim mitchell': 455,
 'ako adams': 457,
 'ako kaluna': 460,
 'akok akok': 462,
 'akrum ahemed': 463,
 'aksel bolin': 464,
 'akwasi yeboah': 467,
 'al amir dawes': 471,
 'al durham': 474,
 'al farouq aminu': 475,
 'al freeman': 476,
 'al rapier': 478,
 'alan griffin': 479,
 'alan herndon': 480,
 'alan jones': 483,
 'alan michael thompson': 484,
 'alan vest': 485,
 'alan williams': 486,
 'alandise harris': 489,
 'alani moore ii': 492,
 'alante fenner': 494,
 'alasdair fraser': 496,
 'albert almanza': 498,
 'albert owens': 500,
 'albert thomas': 503,
 'alberto estwick': 505,
 'alec brown': 507,
 'alec burks': 511,
 'alec kobre': 513,
 'alec peters': 514,
 'alec wintering': 518,
 'aleek pauline': 522,
 'aleem ford': 524,
 'aleer leek': 527,
 'alejo rodriguez': 528,
 'aleksa jugovic': 529,
 'aleksa nikolic': 532,
 'aleksandar dozic': 533,
 'alessandro lever': 534,
 'alex abreu': 538,
 'alex anderson': 540,
 'alex arians': 543,
 'alex austin': 547,
 'alex barcello': 548,
 'alex caldwell': 551,
 'alex caruso': 552,
 'alex copeland': 556,
 'alex davis': 559,
 'alex dragicevich': 560,
 'alex ducas': 561,
 'alex floresca': 562,
 'alex francis': 563,
 'alex franklin': 567,
 'alex garcia mendoza': 568,
 'alex hamilton': 570,
 'alex harris': 573,
 'alex hart': 577,
 'alex hicks': 578,
 'alex hobbs': 580,
 'alex hunter': 583,
 'alex johnson': 587,
 'alex jones': 588,
 'alex king': 589,
 'alex kirk': 592,
 'alex larsson': 594,
 'alex len': 597,
 'alex lomax': 598,
 'alex long': 600,
 'alex marcotullio': 603,
 'alex merkviladze': 604,
 'alex mitola': 606,
 'alex morales': 609,
 'alex murphy': 612,
 "alex o'connell": 613,
 'alex olah': 614,
 'alex oriakhi': 617,
 'alex osborne': 621,
 'alex peacock': 623,
 'alex peterson': 625,
 'alex petrie': 626,
 'alex phillips': 628,
 'alex poythress': 629,
 'alex ramon': 631,
 'alex reese': 632,
 'alex rivera': 633,
 'alex robinson': 636,
 'alex rosenberg': 639,
 'alex rubin': 643,
 'alex smith': 645,
 'alex stepheson': 646,
 'alex thompson': 648,
 'alex tucker': 650,
 'alex tyus': 653,
 'alex vilarino': 655,
 'alex watson': 656,
 'alex welhouse': 658,
 'alex young': 660,
 'alex zampier': 667,
 'alexander aka gorski': 668,
 'alexander barlow': 669,
 'alexander starling': 671,
 'alexis moore': 673,
 'alexis yetna': 674,
 'alfonso plummer': 677,
 'alfonzo houston': 679,
 'alfonzo mckinnie': 680,
 'alfred hollins': 682,
 'alfred jones': 683,
 'algevon eichelberger': 685,
 'ali ali': 686,
 'ali farokhmanesh': 688,
 'alihan demir': 689,
 'alijah martin': 692,
 'alimamy koroma': 693,
 'alize johnson': 695,
 'aljami durham': 697,
 'aljaz kunc': 700,
 'allan chaney': 701,
 'allante holston': 702,
 'allen betrand': 703,
 'allen crabbe': 704,
 'allen flanigan': 707,
 'allen huddleston': 708,
 'allen payne': 711,
 'allen powell': 714,
 'allen roberts': 716,
 'allen smith': 718,
 'allerik freeman': 720,
 'allin blunt': 721,
 "al'lonzo coleman": 723,
 'allonzo trier': 724,
 'allyn cooks': 726,
 'alondes williams': 728,
 'alonzo gaffney': 729,
 'alonzo nelson ododa': 730,
 'alonzo sule': 731,
 'alonzo verge': 732,
 'alonzo verge jr': 733,
 'alonzo walker': 735,
 'aloys cabell': 736,
 'aloysius henry': 737,
 'alpha diallo': 738,
 'alphonso anderson': 742,
 'alphonso dawson': 743,
 'alphonso leary': 744,
 'alshwan hymes': 747,
 'alterique gilbert': 749,
 'alvaro cardenas torre': 752,
 'alvin abreu': 753,
 'alvin mofunanya': 755,
 'alwayne bigby': 756,
 'aly ahmed': 757,
 'aly khalifa': 759,
 'alzee williams': 760,
 'amadi udenyi': 763,
 'amadou sidibe': 764,
 'amadou sow': 767,
 'amanze egekeze': 771,
 'amar stukes': 775,
 'amari davis': 779,
 "amath m'baye": 782,
 'amauri hardy': 784,
 'amaurys fermin': 786,
 'ambrose mosley': 787,
 'amdy fall': 789,
 'ameen tanksley': 790,
 'ameer ali': 794,
 'ameer bennett': 795,
 'ameka akaya': 797,
 'amere may': 798,
 'amida brimah': 799,
 'amile jefferson': 801,
 'amin adamu': 804,
 'amin stevens': 807,
 'aminu mohammed': 809,
 'amir bell': 810,
 'amir celestin': 814,
 'amir coffey': 815,
 'amir gholizadeh': 817,
 'amir johnson': 818,
 'amir spears': 819,
 'amir williams': 820,
 'amorie archibald': 821,
 'amorrow morgan': 825,
 'amos olatayo': 826,
 'amos studivant': 827,
 'amos wilson': 829,
 'amric fields': 831,
 'amu saaka': 832,
 'anas mahmoud': 834,
 'anatoly bose': 835,
 'andell cumberbatch': 837,
 'anders broman': 839,
 'anders nelson': 841,
 'anderson kopp': 842,
 'andre adams': 845,
 'andre armstrong': 846,
 'andre coimbra': 848,
 'andre cornelius': 849,
 'andre curbelo': 851,
 'andre dawkins': 852,
 'andre drummond': 854,
 'andre fox': 855,
 'andre gordon': 858,
 'andre gustavson': 860,
 "andre' hatchett": 861,
 'andre hollins': 864,
 'andre jackson': 868,
 'andre jones': 870,
 'andre kelly': 876,
 'andre kennedy': 878,
 'andre malone': 880,
 'andre marhold': 881,
 'andre nation': 882,
 'andre roberson': 883,
 'andre screen': 886,
 'andre smith': 887,
 'andre snoddy': 890,
 'andre spight': 891,
 'andre stringer': 892,
 'andre walker': 896,
 'andre washington': 902,
 'andre wesson': 903,
 'andre williamson': 905,
 'andre winston': 907,
 'andre wolford': 908,
 'andre yates': 910,
 'andre young': 912,
 'andrei savrasov': 915,
 'andrej jakimovski': 916,
 'andres diaz': 917,
 'andres feliz': 918,
 'andres irarrazabal': 920,
 'andres torres': 921,
 'andrew andrews': 922,
 'andrew beinert': 926,
 'andrew bock': 928,
 'andrew brown': 929,
 'andrew carr': 930,
 'andrew chrabascz': 932,
 'andrew drone': 935,
 'andrew eudy': 936,
 'andrew ferry': 939,
 'andrew fitzgerald': 941,
 'andrew fleming': 943,
 'andrew funk': 948,
 'andrew gabriel': 951,
 'andrew garcia': 952,
 'andrew gonzalez': 954,
 'andrew goudelock': 956,
 'andrew harrison': 958,
 'andrew jackson': 960,
 'andrew jones': 961,
 'andrew jones iii': 965,
 'andrew keister': 967,
 'andrew kostecka': 969,
 'andrew lawrence': 972,
 'andrew lewis': 975,
 'andrew mccarthy': 976,
 'andrew nembhard': 977,
 'andrew nicholas': 981,
 'andrew nicholson': 984,
 'andrew robinson': 987,
 'andrew rogers': 988,
 'andrew rowsey': 989,
 'andrew ryan': 993,
 'andrew smith': 996,
 'andrew taylor': 1001,
 'andrew warren': 1004,
 'andrew white iii': 1006,
 'andrew wiggins': 1008,
 'andrey semenov': 1009,
 'andrien white': 1011,
 'andris misters': 1015,
 'andy brown': 1016,
 'andy buechert': 1017,
 'andy diaz': 1018,
 'andy king': 1020,
 'andy ogide': 1021,
 'andy polka': 1023,
 'andy rautins': 1025,
 'andy van vliet': 1026,
 'anell alexis': 1027,
 'angel delgado': 1028,
 'angel matias': 1032,
 'angel nunez': 1034,
 'angel rivera': 1035,
 'angel rodriguez': 1039,
 'angelo allegri': 1043,
 'angelo caloiaro': 1046,
 'angelo johnson': 1049,
 'angelo warner': 1052,
 'angus brandt': 1056,
 "an'juan wilderness": 1058,
 'anquan hill': 1059,
 'anselm uzuegbunem': 1060,
 'anson winder': 1062,
 'ant nelson': 1063,
 'anthlon bell': 1064,
 'anthony adger': 1065,
 'anthony allison': 1066,
 'anthony avery': 1068,
 'anthony banks': 1069,
 'anthony barber': 1071,
 'anthony beane': 1072,
 'anthony beane jr': 1073,
 'anthony bennett': 1076,
 'anthony bonner': 1077,
 'anthony breeze': 1078,
 'anthony brock': 1079,
 'anthony brown': 1080,
 'anthony campbell': 1084,
 "anthony 'cat' barber": 1086,
 'anthony clemmons': 1088,
 'anthony collins': 1089,
 'anthony cordova': 1093,
 'anthony cousin': 1094,
 'anthony cowan': 1096,
 'anthony cowan jr': 1097,
 'anthony crater': 1100,
 'anthony crump': 1101,
 'anthony dallier': 1103,
 "anthony d'avanzo": 1104,
 'anthony davis': 1105,
 "anthony d'orazio": 1106,
 'anthony downing': 1108,
 'anthony drmic': 1110,
 'anthony durham': 1114,
 'anthony duruji': 1116,
 'anthony edwards': 1120,
 'anthony ervin': 1121,
 'anthony fields': 1124,
 'anthony gaines': 1125,
 'anthony gaston': 1128,
 'anthony gill': 1130,
 'anthony glover': 1133,
 'anthony green': 1134,
 'anthony gurley': 1135,
 'anthony harris': 1137,
 'anthony henderson': 1138,
 'anthony hickey': 1140,
 'anthony hill': 1144,
 'anthony holland': 1148,
 'anthony holliday': 1151,
 'anthony horton': 1153,
 'anthony hubbard': 1154,
 'anthony humpty hitchens': 1156,
 'anthony ireland': 1157,
 'anthony jackson': 1161,
 'anthony james': 1163,
 'anthony johnson': 1166,
 'anthony jones': 1170,
 'anthony lamb': 1172,
 'anthony lawrence ii': 1175,
 'anthony lawrence jr': 1177,
 'anthony lee': 1178,
 'anthony lindauer': 1180,
 'anthony livingston': 1182,
 'anthony marshall': 1185,
 'anthony mathis': 1188,
 'anthony mcdonald': 1191,
 'anthony miles': 1193,
 'anthony minor': 1196,
 'anthony monaco': 1197,
 'anthony morse': 1198,
 'anthony mosley': 1199,
 'anthony murphy': 1202,
 'anthony myers': 1204,
 'anthony myers pate': 1206,
 'anthony myles': 1208,
 'anthony nelson': 1212,
 'anthony nieves': 1215,
 'anthony odunsi': 1216,
 'anthony perez': 1218,
 'anthony polite': 1219,
 'anthony raffa': 1221,
 'anthony roberts': 1224,
 'anthony sally': 1226,
 'anthony selden': 1227,
 'anthony simpson': 1228,
 'anthony smith': 1229,
 'anthony stitt': 1230,
 'anthony tarke': 1233,
 'anthony thomas': 1236,
 'anthony thompson': 1240,
 'anthony townes': 1243,
 'anthony vanhook': 1246,
 'anthony walker': 1248,
 'anthony white jr': 1249,
 'anthony winbush': 1250,
 'anthony wright': 1251,
 'antino jackson': 1253,
 'antione lister': 1256,
 'antoine allen': 1257,
 'antoine davis': 1259,
 'antoine mason': 1263,
 'antoine myers': 1267,
 'antoine pearson': 1269,
 'antoine pittman': 1270,
 'antoine smith jr': 1271,
 'antoine young': 1272,
 'anton beard': 1275,
 'anton dickerson': 1277,
 'anton gill': 1278,
 'anton grady': 1279,
 'anton silver': 1282,
 'anton wilson': 1283,
 'antonio ballard': 1286,
 'antonio barton': 1287,
 'antonio biglow': 1290,
 'antonio blakeney': 1292,
 'antonio bostic': 1294,
 'antonio campbell': 1297,
 'antonio cowart jr': 1299,
 'antonio daye': 1300,
 'antonio daye jr': 1301,
 'antonio flaggs': 1303,
 'antonio green': 1304,
 'antonio hanson': 1311,
 'antonio jenifer': 1312,
 'antonio lofton': 1313,
 'antonio pena': 1315,
 'antonio reeves': 1317,
 'antonio rizzuto': 1320,
 'antonio robinson': 1324,
 'antonio tj madlock': 1326,
 'antonio williams': 1327,
 'antonio woods': 1331,
 'antonius cleveland': 1334,
 'antonnio benton': 1338,
 'antrell charlton': 1339,
 'antwain johnson': 1340,
 'antwaine wiggins': 1342,
 'antwan burrus': 1344,
 'antwan carter': 1347,
 'antwan scott': 1350,
 'antwan space': 1352,
 'antwan walker': 1353,
 'antwoine anderson': 1355,
 'antwon lillard': 1358,
 'antwon portley': 1361,
 'antwone snead': 1365,
 'antwuan butler': 1366,
 'antywan jones': 1369,
 'aqeel quinn': 1370,
 'archie goodwin': 1371,
 'ardarius simmons': 1372,
 'ari stewart': 1373,
 'aric brooks': 1374,
 'aric holman': 1376,
 'ariece perkins': 1379,
 'arinze chidom': 1380,
 'arinze onuaku': 1381,
 'arkadiy mkrtychyan': 1382,
 'arkel lamar': 1384,
 'arlon harper': 1387,
 'armaan franklin': 1391,
 'armando bacot': 1393,
 'armani chaney': 1396,
 'armani cotton': 1398,
 'armani moore': 1401,
 'armel potter': 1403,
 'armel tete': 1406,
 'armon bassett': 1407,
 'armon fletcher': 1408,
 'armon harried': 1411,
 'armon johnson': 1414,
 'armond battle': 1415,
 "ar'mond davis": 1416,
 'armoni brooks': 1417,
 'arnaldo toro': 1419,
 'arnaud william adala moto': 1420,
 'arnett moultrie': 1422,
 'arnold fripp': 1424,
 'arnold louis': 1425,
 'arsalan kazemi': 1428,
 'arsenio williams': 1432,
 'art bernardi': 1433,
 'art steward': 1434,
 'artem tavakalyan': 1436,
 'arthur edwards': 1437,
 'arthur johnson': 1438,
 'arthur kaluma': 1439,
 'arthur wade': 1440,
 'artsiom parakhouski': 1441,
 'artur konontsuk': 1442,
 'artur labinowicz': 1443,
 'arturs bremers': 1445,
 'asad lamot': 1446,
 'asante gist': 1447,
 'asauhn dixon tatum': 1450,
 'asbjorn midtgaard': 1451,
 'asenso ampim': 1452,
 'ash yacoubou': 1453,
 'ashante shivers': 1455,
 'ashen ward': 1456,
 'ashley hamilton': 1459,
 'ashton gibbs': 1460,
 'ashton hagans': 1463,
 'ashton mitchell': 1465,
 'ashton moore': 1466,
 'ashton pankey': 1470,
 'asim mcqueen': 1472,
 'askia booker': 1473,
 'assane sene': 1477,
 'atem bior': 1478,
 'atin wright': 1479,
 "a'torri shine": 1480,
 'aubrey coleman': 1482,
 'aubrey dawkins': 1483,
 'aubrey williams': 1484,
 "au'diese toney": 1486,
 'august haas': 1490,
 'augustine ene': 1491,
 'augustine rubit': 1492,
 'augustus gilchrist': 1496,
 'aundre jackson': 1498,
 'auraum nuiriankh': 1499,
 'aurimas majauskas': 1500,
 'austen awosika': 1501,
 'austin ajukwa': 1504,
 'austin akers': 1505,
 'austin anderson': 1506,
 'austin arians': 1507,
 'austin butler': 1510,
 'austin chatman': 1515,
 'austin cooke': 1518,
 'austin dahn': 1520,
 'austin dasent': 1522,
 'austin dufault': 1523,
 'austin freeman': 1526,
 'austin hamilton': 1528,
 'austin harvell': 1529,
 'austin hill': 1530,
 'austin hollins': 1531,
 'austin howard': 1534,
 'austin johnson': 1535,
 'austin kenon': 1536,
 'austin kilpatrick': 1538,
 'austin loop': 1539,
 'austin luke': 1542,
 'austin mcbroom': 1545,
 'austin mccullough': 1549,
 'austin morgan': 1550,
 'austin nehls': 1553,
 'austin nichols': 1556,
 'austin patterson': 1558,
 'austin pennick': 1559,
 'austin phyfe': 1560,
 'austin price': 1562,
 'austin ramljak': 1566,
 'austin reaves': 1568,
 'austin richie': 1571,
 'austin rivers': 1574,
 'austin ruder': 1575,
 'austin smellie': 1578,
 'austin stewart': 1581,
 'austin thornton': 1582,
 'austin tilghman': 1583,
 'austin tillotson': 1584,
 'austin trice': 1588,
 'austin vereen': 1589,
 'austin white': 1590,
 'austin wiley': 1591,
 'austin williams': 1592,
 'austin witter': 1596,
 'auston barnes': 1599,
 "a'uston calhoun": 1601,
 'avery anderson iii': 1604,
 'avery bradley': 1606,
 'avery johnson': 1607,
 'avery lomax': 1609,
 'avery moore': 1610,
 'avery sullivan': 1613,
 'avery ugba': 1615,
 'avery woodson': 1616,
 'averyl ugba': 1619,
 'avi toomer': 1620,
 'avry holmes': 1622,
 'axel mpoyo': 1625,
 'ayibakuro preh': 1627,
 'ayinde hikim': 1628,
 'ayo akinwole': 1630,
 'ayo dosunmu': 1632,
 'ayodeji egbeyemi': 1635,
 'ayron hardy': 1637,
 'azar swain': 1639,
 "aziz n'diaye": 1641,
 'azuolas tubelis': 1643,
 'b artis white': 1645,
 'babatunde olumuyiwa': 1647,
 'badou diagne': 1648,
 'bakari copeland': 1652,
 'bakari evelyn': 1654,
 'bakari lastrap': 1656,
 'bakari lewis': 1657,
 'bakary konate': 1659,
 'balint mocsan': 1660,
 'bam bowman': 1662,
 'bandja sy': 1663,
 'barret benson': 1665,
 'barrington stevens iii': 1666,
 'barry brown': 1669,
 'barry brown jr': 1671,
 'barry latham': 1673,
 'barry stewart': 1675,
 'bas leyte': 1676,
 'bashir ahmed': 1677,
 'baylee steele': 1679,
 'baylor scheierman': 1681,
 'beau beech': 1684,
 'beau levesque': 1688,
 'beejay anya': 1690,
 'ben aird': 1691,
 'ben allen': 1695,
 'ben averkamp': 1696,
 'ben bentil': 1699,
 'ben botts': 1701,
 'ben brust': 1703,
 'ben cherry': 1706,
 'ben clifford': 1707,
 'ben coupet jr': 1708,
 'ben dickinson': 1711,
 'ben dillard': 1712,
 'ben dowdell': 1714,
 'ben drayton': 1715,
 'ben eblen': 1718,
 'ben emelogu ii': 1719,
 'ben finney': 1721,
 'ben hansbrough': 1723,
 'ben harvey': 1725,
 'ben hazel': 1727,
 'ben johnson': 1728,
 'ben krikke': 1729,
 'ben lammers': 1731,
 'ben louis': 1733,
 'ben martin': 1734,
 'ben mclemore': 1735,
 'ben millaud meunier': 1736,
 'ben mockford': 1737,
 'ben moore': 1740,

In [159]:
id_df = []
for name in names:
    id_df.append(names_id[name])

college_df['id'] = id_df
college_df

,pos,year,player_name,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,rimmade/(rimmade+rimmiss),midmade/(midmade+midmiss),drtg,dporpag,stops,bpm,obpm,dbpm,gbpm,id
0,Pure PG,2016,aakim saintil,99.7,25.1,42.4,51.19,1.4,6.9,30.7,...,0.4955,0.3651,105.9150,1.56664,159.624,-3.26644,0.030543,-3.296980,-2.77093,0
1,Scoring PG,2014,aakim saintil,90.7,18.8,38.8,45.78,2.4,7.2,16.8,...,0.4000,0.2941,107.2760,1.69099,104.720,-2.51437,-1.580690,-0.933676,-3.76000,0
2,Scoring PG,2020,aamahne santos,91.3,16.9,43.4,45.46,1.0,7.5,17.7,...,0.3333,0.4286,102.4780,2.24427,127.305,-2.76325,-1.505430,-1.257820,-3.09113,2
3,Combo G,2019,aamahne santos,94.8,13.6,44.5,48.35,1.3,5.7,13.6,...,0.4400,0.3404,110.1800,1.70602,124.297,-4.17925,-1.570270,-2.608980,-4.17229,2
4,Pure PG,2010,aamir mccleary,83.4,27.1,39.2,43.97,1.9,12.7,36.7,...,0.4524,0.3162,109.0140,1.84381,123.324,-3.70329,-1.809020,-1.894260,-4.48713,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22432,PF/C,2019,zylan cheatham,103.4,21.3,55.4,57.81,7.3,27.0,18.9,...,0.6918,0.2619,95.2679,4.08030,261.172,5.30060,0.879435,4.421170,4.41700,22432
22433,C,2016,zylan cheatham,102.3,21.5,53.1,59.30,9.0,19.6,9.7,...,0.6931,0.2653,88.6883,3.01983,157.194,3.48201,-0.858994,4.341000,3.67966,22432
22434,PF/C,2017,zylan cheatham,108.6,22.3,52.6,58.89,10.9,19.4,13.0,...,0.6303,0.2889,90.4961,3.06665,149.784,5.01479,0.794398,4.220390,3.94168,22432
22435,Scoring PG,2021,zyon pullin,113.0,22.3,53.1,56.48,1.4,16.0,28.8,...,0.5750,0.4487,95.7722,3.27284,123.635,2.98239,1.924740,1.057650,3.49492,22435
22436,Combo G,2022,zyon pullin,107.6,25.0,50.4,56.84,1.4,17.6,26.4,...,0.6125,0.4460,97.6472,3.24824,155.009,1.96414,1.433930,0.530201,2.60952,22435

In [161]:
college_df.to_csv('college_df_final_scores.csv')